"""Deterministic closed-operation interpreter for NEXUS Trap YAML v1."""

from __future__ import annotations

from collections import Counter
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from enum import Enum
import hashlib
import json
from types import MappingProxyType
import re
from typing import Any, Callable

from nexus_runtime.canonical import canonical_json
from nexus_runtime.trap.yaml_dsl import (
    CanonicalTrapProgram,
    SCHEMA_VERSION,
    canonicalize_trap_program,
)


INTERPRETER_VERSION = "nexus-trap-yaml-interpreter/1"
EXECUTION_SCHEMA = "nexus-trap-execution/1"
REPORT_SCHEMA = "nexus-trap-council-report/1"
CANDIDATE_SCHEMA = "nexus-trap-candidate/1"
PRIMARY_FIXTURE_ID = "mixed-observation-speculation"
_TRAP_REF = re.compile(r"^trap:[0-9a-f]{64}$")


class TrapYAMLRuntimeError(ValueError):
    """A deterministic interpreter failure with a stable error code."""

    def __init__(self, code: str, message: str) -> None:
        self.code = code
        super().__init__(message)


def _runtime_error(code: str, message: str) -> None:
    raise TrapYAMLRuntimeError(code, message)


def _json_copy(value: Any) -> Any:
    try:
        return json.loads(canonical_json(value))
    except (TypeError, ValueError, OverflowError, RecursionError) as exc:
        raise TrapYAMLRuntimeError(
            "trap_yaml_invalid_fixture",
            "synthetic fixture must contain bounded JSON primitives",
        ) from exc


def _freeze(value: Any) -> Any:
    if type(value) is dict:
        return MappingProxyType({key: _freeze(child) for key, child in value.items()})
    if type(value) is list:
        return tuple(_freeze(child) for child in value)
    return value


def _thaw(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _thaw(child) for key, child in value.items()}
    if isinstance(value, tuple):
        return [_thaw(child) for child in value]
    if isinstance(value, list):
        return [_thaw(child) for child in value]
    return value


@dataclass(frozen=True)
class TrapFixture:
    fixture_id: str
    payload: Mapping[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return _thaw(self.payload)


def _make_fixture(fixture_id: str, payload: Mapping[str, Any]) -> TrapFixture:
    copied = _json_copy({"fixture_id": fixture_id, **dict(payload)})
    return TrapFixture(fixture_id, _freeze(copied))


_FIXTURE_VALUES = (
    _make_fixture(
        PRIMARY_FIXTURE_ID,
        {
            "question": "What does the synthetic signal establish?",
            "evidence": [
                {
                    "id": "obs-1",
                    "kind": "observation",
                    "text": "The synthetic detector recorded a narrow peak at 431 Hz.",
                },
                {
                    "id": "int-1",
                    "kind": "interpretation",
                    "text": "The peak may reflect the fixture's transform settings.",
                },
                {
                    "id": "spec-1",
                    "kind": "speculation",
                    "text": "The peak proves a universal tuning constant.",
                },
            ],
            "unknowns": ["Whether the peak persists under an independently specified transform."],
            "hypotheses": [
                {
                    "id": "hyp-1",
                    "text": "The peak is generated by the fixture transform.",
                    "falsifier": "A preregistered alternate transform yields the same peak.",
                }
            ],
            "tests": [
                {"id": "test-1", "text": "Repeat with a preregistered transform.", "discrimination": 3, "cost": 1}
            ],
        },
    ),
    _make_fixture(
        "contradictory-evidence",
        {
            "question": "Which synthetic reading is supported?",
            "evidence": [
                {"id": "obs-a", "kind": "observation", "text": "Sensor A reports the gate open."},
                {"id": "obs-b", "kind": "observation", "text": "Sensor B reports the gate closed."},
            ],
            "contradictions": ["obs-a conflicts with obs-b"],
            "unknowns": ["Which sensor retained calibration."],
            "hypotheses": [
                {
                    "id": "hyp-calibration",
                    "text": "One sensor lost calibration.",
                    "falsifier": "Both sensors pass an independent calibration check.",
                }
            ],
            "tests": [
                {"id": "calibrate", "text": "Run the fixed calibration fixture.", "discrimination": 3, "cost": 1}
            ],
        },
    ),
    _make_fixture(
        "missing-observation",
        {
            "question": "Did the synthetic event occur?",
            "evidence": [
                {"id": "claim-1", "kind": "interpretation", "text": "The event probably occurred."}
            ],
            "unknowns": ["No direct observation of the event is present."],
            "hypotheses": [],
            "tests": [
                {"id": "observe", "text": "Collect a direct synthetic observation.", "discrimination": 3, "cost": 2}
            ],
        },
    ),
    _make_fixture(
        "two-competing-hypotheses",
        {
            "question": "What produced the synthetic trace?",
            "evidence": [
                {"id": "trace", "kind": "observation", "text": "A periodic trace appears in the fixture."}
            ],
            "unknowns": ["Whether the source or the transform is periodic."],
            "hypotheses": [
                {
                    "id": "source",
                    "text": "The synthetic source is periodic.",
                    "falsifier": "The raw source fixture contains no periodicity.",
                },
                {
                    "id": "transform",
                    "text": "The transform introduces periodicity.",
                    "falsifier": "An identity transform preserves the same trace.",
                },
            ],
            "tests": [
                {"id": "raw", "text": "Inspect the raw source fixture.", "discrimination": 3, "cost": 1},
                {"id": "identity", "text": "Run the identity transform.", "discrimination": 3, "cost": 2},
            ],
        },
    ),
    _make_fixture(
        "test-ranking-problem",
        {
            "question": "Which synthetic test should run first?",
            "evidence": [
                {"id": "baseline", "kind": "observation", "text": "The baseline fixture is inconclusive."}
            ],
            "unknowns": ["Which of two hypotheses generated the baseline."],
            "hypotheses": [],
            "tests": [
                {"id": "cheap-low", "text": "Cheap low-discrimination test.", "discrimination": 1, "cost": 1},
                {"id": "cheap-high", "text": "Cheap high-discrimination test.", "discrimination": 3, "cost": 1},
                {"id": "costly-high", "text": "Costly high-discrimination test.", "discrimination": 3, "cost": 3},
            ],
        },
    ),
    _make_fixture(
        "unfalsifiable-claim",
        {
            "question": "Can the synthetic claim be falsified?",
            "evidence": [
                {
                    "id": "claim",
                    "kind": "speculation",
                    "text": "An undetectable cause controls every possible result.",
                }
            ],
            "unknowns": ["No observation can distinguish the asserted cause from its absence."],
            "hypotheses": [
                {"id": "hidden-cause", "text": "An undetectable cause controls every result.", "falsifier": None}
            ],
            "tests": [],
        },
    ),
)

FIXTURES: Mapping[str, TrapFixture] = MappingProxyType(
    {fixture.fixture_id: fixture for fixture in _FIXTURE_VALUES}
)
HIDDEN_FIXTURE_IDS = tuple(fixture.fixture_id for fixture in _FIXTURE_VALUES if fixture.fixture_id != PRIMARY_FIXTURE_ID)


@dataclass(frozen=True)
class TrapExecutionResult:
    program_sha256: str
    fixture_id: str
    report: Mapping[str, Any]
    result_sha256: str
    interpreter_version: str = INTERPRETER_VERSION
    schema: str = EXECUTION_SCHEMA
    success: bool = True

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema": self.schema,
            "success": self.success,
            "program_sha256": self.program_sha256,
            "fixture_id": self.fixture_id,
            "interpreter_version": self.interpreter_version,
            "result_sha256": self.result_sha256,
            "report": _thaw(self.report),
        }


@dataclass(frozen=True)
class TrapReleaseValidation:
    program_sha256: str
    primary_fixture_id: str
    status: str
    first_run_attempts: int
    executions: tuple[TrapExecutionResult, ...] = ()
    failed_fixture_id: str | None = None
    error_code: str | None = None

    @property
    def valid_and_executes(self) -> bool:
        return self.status == "VALID_AND_EXECUTES"

    @property
    def fixture_result_hashes(self) -> dict[str, str]:
        return {result.fixture_id: result.result_sha256 for result in self.executions}

    def to_dict(self) -> dict[str, Any]:
        return {
            "program_sha256": self.program_sha256,
            "primary_fixture_id": self.primary_fixture_id,
            "status": self.status,
            "first_run_attempts": self.first_run_attempts,
            "valid_and_executes": self.valid_and_executes,
            "failed_fixture_id": self.failed_fixture_id,
            "error_code": self.error_code,
            "fixture_result_hashes": self.fixture_result_hashes,
        }


class UtilityBallot(str, Enum):
    USEFUL = "USEFUL"
    USEFUL_WITH_CHANGES = "USEFUL_WITH_CHANGES"
    NOT_USEFUL = "NOT_USEFUL"


@dataclass(frozen=True)
class UtilityDecision:
    ballots: Mapping[str, str]
    counts: Mapping[str, int]
    supporting_votes: int
    total_votes: int
    required_supporting_votes: int
    accepted: bool
    status: str
    threshold_numerator: int = 2
    threshold_denominator: int = 3

    def to_dict(self) -> dict[str, Any]:
        return {
            "ballots": dict(self.ballots),
            "counts": dict(self.counts),
            "supporting_votes": self.supporting_votes,
            "total_votes": self.total_votes,
            "required_supporting_votes": self.required_supporting_votes,
            "threshold": {"numerator": self.threshold_numerator, "denominator": self.threshold_denominator},
            "accepted": self.accepted,
            "status": self.status,
        }


def _canonical_program(program: CanonicalTrapProgram | Mapping[str, Any]) -> CanonicalTrapProgram:
    if isinstance(program, CanonicalTrapProgram):
        checked = canonicalize_trap_program(program.tree)
        if checked.program_sha256 != program.program_sha256 or checked.canonical_json != program.canonical_json:
            _runtime_error("trap_yaml_program_identity_mismatch", "canonical program identity does not match its tree")
        return checked
    if isinstance(program, Mapping):
        return canonicalize_trap_program(program)
    raise TypeError("program must be CanonicalTrapProgram or a mapping")


def _resolve_fixture(fixture: TrapFixture | str | Mapping[str, Any]) -> TrapFixture:
    if type(fixture) is str:
        try:
            return FIXTURES[fixture]
        except KeyError as exc:
            raise TrapYAMLRuntimeError("trap_yaml_unknown_fixture", "unknown synthetic fixture") from exc
    if isinstance(fixture, TrapFixture):
        copied = _thaw(fixture.payload)
        return _make_fixture(
            fixture.fixture_id,
            {key: value for key, value in copied.items() if key != "fixture_id"},
        )
    if isinstance(fixture, Mapping):
        copied = _json_copy(dict(fixture))
        fixture_id = copied.get("fixture_id")
        if type(fixture_id) is not str or not re.fullmatch(r"[a-z][a-z0-9-]{0,63}", fixture_id):
            _runtime_error("trap_yaml_invalid_fixture", "synthetic fixture requires a bounded fixture_id")
        return _make_fixture(fixture_id, {key: value for key, value in copied.items() if key != "fixture_id"})
    raise TypeError("fixture must be a fixture id, TrapFixture, or mapping")


def _text_items(value: Any) -> list[str]:
    if not isinstance(value, (list, tuple)):
        return []
    result: list[str] = []
    for item in value:
        if type(item) is str:
            result.append(item)
        elif isinstance(item, Mapping) and type(item.get("text")) is str:
            result.append(item["text"])
    return result


def _evidence(fixture: Mapping[str, Any]) -> list[dict[str, str]]:
    raw = fixture.get("evidence", ())
    if not isinstance(raw, (list, tuple)):
        return []
    result: list[dict[str, str]] = []
    for index, item in enumerate(raw):
        if type(item) is str:
            result.append({"id": f"evidence-{index + 1}", "kind": "observation", "text": item})
        elif isinstance(item, Mapping) and type(item.get("text")) is str:
            result.append(
                {
                    "id": str(item.get("id", f"evidence-{index + 1}")),
                    "kind": str(item.get("kind", "observation")),
                    "text": item["text"],
                }
            )
    return result


def _summarize(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    evidence = _evidence(fixture)
    if not evidence:
        state["summary"] = "No direct synthetic evidence was supplied."
        return
    joined = " ".join(item["text"] for item in evidence[:3])
    state["summary"] = f"{len(evidence)} evidence item(s): {joined}"


def _separate(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    categories = step["categories"]
    grouped = {category: [] for category in categories}
    for item in _evidence(fixture):
        if item["kind"] in grouped:
            grouped[item["kind"]].append(item["text"])
    state["claims"] = grouped


def _compare(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    claims = _evidence(fixture)
    state["comparisons"] = [
        f"{claims[index]['id']} compared with {claims[index + 1]['id']}"
        for index in range(max(0, len(claims) - 1))
    ]


def _unknowns(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    values = _text_items(fixture.get("unknowns", ()))
    if not values and not any(item["kind"] == "observation" for item in _evidence(fixture)):
        values = ["A direct synthetic observation is missing."]
    state["unknowns"] = values


def _contradictions(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    state["contradictions"] = _text_items(fixture.get("contradictions", ()))


def _hypotheses(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    values = _text_items(fixture.get("hypotheses", ()))
    if not values:
        values = ["The available synthetic evidence is insufficient to select a hypothesis."]
    state["hypotheses"] = values


def _falsifiers(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    values: list[str] = []
    raw = fixture.get("hypotheses", ())
    if isinstance(raw, (list, tuple)):
        for item in raw:
            if isinstance(item, Mapping) and type(item.get("falsifier")) is str:
                values.append(item["falsifier"])
    if not values:
        values = ["No discriminating falsifier is encoded by this synthetic fixture."]
    state["falsifiers"] = values


def _tests(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    values = _text_items(fixture.get("tests", ()))
    if not values:
        values = ["No valid discriminating test is available for this synthetic claim."]
    state["tests"] = values


def _rank_tests(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    ranked: list[tuple[int, int, str, str]] = []
    raw = fixture.get("tests", ())
    if isinstance(raw, (list, tuple)):
        for index, item in enumerate(raw):
            if not isinstance(item, Mapping) or type(item.get("text")) is not str:
                continue
            discrimination = item.get("discrimination", 0)
            cost = item.get("cost", 0)
            if type(discrimination) is not int or type(cost) is not int:
                _runtime_error("trap_yaml_invalid_fixture", "test ranking values must be integers")
            ranked.append(
                (-discrimination, cost, str(item.get("id", f"test-{index + 1}")), item["text"])
            )
    ranked.sort()
    state["ranked_tests"] = [item[3] for item in ranked]


def _emit_report(state: dict[str, Any], fixture: Mapping[str, Any], step: Mapping[str, Any]) -> None:
    state["emitted"] = True


_OPERATION_REGISTRY: Mapping[str, Callable[[dict[str, Any], Mapping[str, Any], Mapping[str, Any]], None]] = MappingProxyType(
    {
        "summarize_evidence": _summarize,
        "separate_claims": _separate,
        "compare_claims": _compare,
        "identify_unknowns": _unknowns,
        "find_contradictions": _contradictions,
        "propose_hypothesis": _hypotheses,
        "propose_falsifier": _falsifiers,
        "propose_test": _tests,
        "rank_tests": _rank_tests,
        "emit_report": _emit_report,
    }
)


def _report(program: CanonicalTrapProgram, fixture: TrapFixture, state: Mapping[str, Any]) -> dict[str, Any]:
    report = {
        "schema": REPORT_SCHEMA,
        "fixture_id": fixture.fixture_id,
        "program_sha256": program.program_sha256,
        "summary": state.get("summary", "No summary operation was requested."),
        "claims": state.get("claims", {}),
        "comparisons": state.get("comparisons", []),
        "unknowns": state.get("unknowns", []),
        "contradictions": state.get("contradictions", []),
        "hypotheses": state.get("hypotheses", []),
        "falsifiers": state.get("falsifiers", []),
        "tests": state.get("tests", []),
        "ranked_tests": state.get("ranked_tests", []),
    }
    copied = _json_copy(report)
    if copied.get("schema") != REPORT_SCHEMA or type(copied.get("summary")) is not str:
        _runtime_error("trap_yaml_invalid_report", "interpreter did not emit a schema-valid council_report")
    return copied


def execute_program(
    program: CanonicalTrapProgram | Mapping[str, Any],
    fixture: TrapFixture | str | Mapping[str, Any],
) -> TrapExecutionResult:
    """Execute a canonical program once against one immutable fixture snapshot."""

    canonical = _canonical_program(program)
    resolved = _resolve_fixture(fixture)
    fixture_tree = resolved.to_dict()
    missing_inputs = [name for name in canonical.tree["inputs"] if name not in fixture_tree]
    if missing_inputs:
        _runtime_error("trap_yaml_missing_input", "synthetic fixture does not provide a declared input")

    state: dict[str, Any] = {}
    for step in canonical.tree["steps"]:
        operation = _OPERATION_REGISTRY.get(step["op"])
        if operation is None:  # defense in depth after closed schema validation
            _runtime_error("trap_yaml_unknown_operation", "Trap YAML operation is not in the closed registry")
        operation(state, resolved.payload, step)
    if state.get("emitted") is not True:
        _runtime_error("trap_yaml_invalid_report", "program did not emit a council_report")
    report = _report(canonical, resolved, state)
    identity = {
        "program_sha256": canonical.program_sha256,
        "fixture_id": resolved.fixture_id,
        "interpreter_version": INTERPRETER_VERSION,
        "report": report,
    }
    digest = hashlib.sha256(canonical_json(identity).encode("utf-8")).hexdigest()
    return TrapExecutionResult(
        program_sha256=canonical.program_sha256,
        fixture_id=resolved.fixture_id,
        report=_freeze(report),
        result_sha256=digest,
    )


def run_release_validation(
    program: CanonicalTrapProgram | Mapping[str, Any],
    primary_fixture: TrapFixture | str | Mapping[str, Any] = PRIMARY_FIXTURE_ID,
    *,
    hidden_fixture_ids: Sequence[str] | None = None,
) -> TrapReleaseValidation:
    """Perform one primary attempt, then the deterministic hidden fixture suite."""

    canonical = _canonical_program(program)
    resolved_primary = _resolve_fixture(primary_fixture)
    results: list[TrapExecutionResult] = []
    try:
        results.append(execute_program(canonical, resolved_primary))
    except Exception as exc:
        code = exc.code if isinstance(exc, TrapYAMLRuntimeError) else "trap_yaml_first_run_failed"
        return TrapReleaseValidation(
            canonical.program_sha256,
            resolved_primary.fixture_id,
            "trap_yaml_first_run_failed",
            1,
            error_code=code,
            failed_fixture_id=resolved_primary.fixture_id,
        )

    fixture_ids = HIDDEN_FIXTURE_IDS if hidden_fixture_ids is None else tuple(hidden_fixture_ids)
    seen = {resolved_primary.fixture_id}
    for fixture_id in fixture_ids:
        if fixture_id in seen:
            continue
        seen.add(fixture_id)
        try:
            results.append(execute_program(canonical, fixture_id))
        except Exception as exc:
            code = exc.code if isinstance(exc, TrapYAMLRuntimeError) else "trap_yaml_hidden_fixture_failed"
            return TrapReleaseValidation(
                canonical.program_sha256,
                resolved_primary.fixture_id,
                "trap_yaml_hidden_fixture_failed",
                1,
                tuple(results),
                fixture_id,
                code,
            )
    return TrapReleaseValidation(
        canonical.program_sha256,
        resolved_primary.fixture_id,
        "VALID_AND_EXECUTES",
        1,
        tuple(results),
    )


def decide_utility(ballots: Mapping[str, str] | Sequence[str]) -> UtilityDecision:
    """Apply the exact ordinary two-thirds threshold using integer arithmetic."""

    if isinstance(ballots, Mapping):
        normalized = {str(member): value for member, value in ballots.items()}
    elif isinstance(ballots, Sequence) and not isinstance(ballots, (str, bytes, bytearray)):
        normalized = {f"voter-{index + 1:03d}": value for index, value in enumerate(ballots)}
    else:
        raise TypeError("ballots must be a mapping or sequence")
    if not normalized:
        _runtime_error("trap_utility_invalid_ballots", "utility vote requires at least one ballot")
    allowed = {ballot.value for ballot in UtilityBallot}
    if any(type(value) is not str or value not in allowed for value in normalized.values()):
        _runtime_error("trap_utility_invalid_ballots", "unknown utility ballot")
    ordered = dict(sorted(normalized.items()))
    counts = Counter(ordered.values())
    supporting = counts[UtilityBallot.USEFUL.value] + counts[UtilityBallot.USEFUL_WITH_CHANGES.value]
    total = len(ordered)
    accepted = supporting * 3 >= total * 2
    required = (total * 2 + 2) // 3
    count_tree = {ballot.value: counts[ballot.value] for ballot in UtilityBallot}
    return UtilityDecision(
        MappingProxyType(ordered),
        MappingProxyType(count_tree),
        supporting,
        total,
        required,
        accepted,
        "ACCEPTED" if accepted else "REJECTED",
    )


def create_candidate_artifact(
    program: CanonicalTrapProgram | Mapping[str, Any],
    validation: TrapReleaseValidation,
    utility: UtilityDecision,
    incident_ref: str,
) -> dict[str, Any]:
    """Create inert quarantine data; this helper has no promotion side effect."""

    canonical = _canonical_program(program)
    if not validation.valid_and_executes or validation.program_sha256 != canonical.program_sha256:
        _runtime_error("trap_candidate_not_eligible", "candidate requires matching deterministic validation")
    if not utility.accepted:
        _runtime_error("trap_candidate_not_eligible", "candidate requires an accepted utility vote")
    if type(incident_ref) is not str or not _TRAP_REF.fullmatch(incident_ref):
        _runtime_error("trap_candidate_invalid_incident", "candidate incident_ref must be a trap reference")
    artifact: dict[str, Any] = {
        "type": "trap_candidate_artifact",
        "schema": CANDIDATE_SCHEMA,
        "canonical_program": json.loads(canonical.canonical_json),
        "program_sha256": canonical.program_sha256,
        "schema_version": SCHEMA_VERSION,
        "interpreter_version": INTERPRETER_VERSION,
        "fixture_result_hashes": dict(sorted(validation.fixture_result_hashes.items())),
        "utility_vote": utility.to_dict(),
        "incident_ref": incident_ref,
        "synthetic_origin": True,
        "security_deception_artifact": True,
        "quarantine_status": "INERT_CANDIDATE",
        "execution_enabled": False,
        "automatic_import": False,
        "requires_explicit_operator_action": True,
        "requires_fresh_external_validation": True,
    }
    artifact["candidate_sha256"] = hashlib.sha256(canonical_json(artifact).encode("utf-8")).hexdigest()
    return artifact


create_inert_candidate_artifact = create_candidate_artifact
utility_vote = decide_utility


__all__ = [
    "CANDIDATE_SCHEMA",
    "EXECUTION_SCHEMA",
    "FIXTURES",
    "HIDDEN_FIXTURE_IDS",
    "INTERPRETER_VERSION",
    "PRIMARY_FIXTURE_ID",
    "REPORT_SCHEMA",
    "TrapExecutionResult",
    "TrapFixture",
    "TrapReleaseValidation",
    "TrapYAMLRuntimeError",
    "UtilityBallot",
    "UtilityDecision",
    "create_candidate_artifact",
    "create_inert_candidate_artifact",
    "decide_utility",
    "execute_program",
    "run_release_validation",
    "utility_vote",
]
